## Exploratory Data Analysis & Feature Engineering

Required imports for sending API calls and parsing the data

In [ ]:
import re
import time
import arxiv
import json
import hashlib
import pandas as pd
import urllib.request as libreq
from pypdf import PdfReader
from pathlib import Path
from datetime import datetime, timezone
from urllib.error import HTTPError

client = arxiv.Client()

Install `arxiv`, `pandas`, and `pypdf` in your notebook environment (`pip install arxiv pandas pypdf`), then use the metadata collection and PDF download cells to download the papers locally. If you encounter a rate-limit error, just resume whenever possible.

Use `notebooks/` as your working directory and go through the notebook sequentially, running only the cells needed for your task and their prerequisites. 

Do not use **Run All**, skip PDF downloads when files are already available, and run **Optional File Cleanup** only if needed.

### Data Search Areas

Set paper target areas and build search queries for each collection area.

In [3]:
total_papers = 100 # divide into 70% business areas and 30% general research
business_area_total = round(total_papers * 0.7)
business_area_split = business_area_total // 7
general_split = total_papers - business_area_total

collection_areas = {
    "document_analysis_and_knowledge_access": {
        "target": business_area_split,
        "keywords": [
            "document understanding",
            "information extraction",
            "retrieval augmented generation",
            "table understanding",
        ]
    },
    "workflow_automation": {
        "target": business_area_split,
        "keywords": [
            "ai agents",
            "tool use",
            "human oversight",
            "process automation",
        ]
    },
    "ai_reliability_governance": {
        "target": business_area_split,
        "keywords": [
            "hallucination detection",
            "explainable AI",
            "algorithmic bias",
            "LLM evaluation"
        ]
    },
    "finance_risk_analytics": {
        "target": business_area_split,
        "keywords": [
            "financial forecasting",
            "risk assessment",
            "fraud detection",
            "financial document analysis"
        ]
    },
    "operations_supply_chain": {
        "target": business_area_split,
        "keywords": [
            "supply chain optimization",
            "inventory management",
            "logistics planning",
            "demand forecasting"
        ]
    },
    "customer_service": {
        "target": business_area_split,
        "keywords": [
            "customer support",
            "conversational Agents",
            "sentiment analysis",
            "customer feedback analysis"
        ]
    },
    "technology_implementation": {
        "target": business_area_split,
        "keywords": [
            "model deployment",
            "model efficiency",
            "model routing",
            "efficient inference"
        ]
    },
    "general": {
        "target": general_split,
        "keywords": []
    }
}

def get_search_query(keyword_list: list[str]) -> str:

    if not keyword_list:
        return (
            "(cat:cs.AI OR cat:cs.LG OR cat:cs.CL "
            "OR cat:cs.IR OR cat:cs.CV)"
        )

    search_terms = [f'abs:"{keyword}"' for keyword in keyword_list]
    combined_terms = " OR ".join(search_terms)

    return f"({combined_terms})"

for area_name, settings in collection_areas.items():
    query = get_search_query(settings["keywords"])
    print(area_name)
    print(query)
    print()

document_analysis_and_knowledge_access
(abs:"document understanding" OR abs:"information extraction" OR abs:"retrieval augmented generation" OR abs:"table understanding")

workflow_automation
(abs:"ai agents" OR abs:"tool use" OR abs:"human oversight" OR abs:"process automation")

ai_reliability_governance
(abs:"hallucination detection" OR abs:"explainable AI" OR abs:"algorithmic bias" OR abs:"LLM evaluation")

finance_risk_analytics
(abs:"financial forecasting" OR abs:"risk assessment" OR abs:"fraud detection" OR abs:"financial document analysis")

operations_supply_chain
(abs:"supply chain optimization" OR abs:"inventory management" OR abs:"logistics planning" OR abs:"demand forecasting")

customer_service
(abs:"customer support" OR abs:"conversational Agents" OR abs:"sentiment analysis" OR abs:"customer feedback analysis")

technology_implementation
(abs:"model deployment" OR abs:"model efficiency" OR abs:"model routing" OR abs:"efficient inference")

general
(cat:cs.AI OR cat:cs.LG OR cat:cs.CL OR cat:cs.IR OR cat:cs.CV)

### Search Helpers

Define cache handling, metadata conversion, and the search-and-save function.

In [4]:
metadata_dr = Path("arxiv_data") / "metadata"

def get_cache_path(area_name: str, query: str, max_results: int) -> Path:
    
    search_settings = {
        "query": query,
        "max_results": max_results,
        "sort_by": "submittedDate",
        "sort_order": "descending"
    }

 
    settings_text = json.dumps(search_settings, sort_keys=True)
    fingerprint = hashlib.sha256(settings_text.encode("utf-8")).hexdigest()[:16]

    cache_filename = f"{area_name}_{fingerprint}.json"

    return metadata_dr / area_name / cache_filename


def load_cached_search(area_name: str, query: str, max_results: int):
    
    cache_path = get_cache_path(area_name, query, max_results)

    if (not cache_path.exists()):
        return None

    cached_text = cache_path.read_text(encoding="utf-8")

    cached_data = json.loads(cached_text)

    print(f"Loaded cached results from {cache_path}")
    return cached_data


def paper_to_dict(paper: arxiv.Result) -> dict:

    return {
        "id": paper.get_short_id(),
        "title": paper.title,

        "abstract": paper.summary,
        "authors": [author.name for author in paper.authors],

        "published": paper.published.isoformat(),
        "updated": paper.updated.isoformat(),

        "source_url": paper.entry_id,
        "pdf_url": paper.pdf_url,
        "primary_category": paper.primary_category,
        "arxiv_categories": paper.categories,
        "doi": paper.doi,
        "journal_ref": paper.journal_ref,
    }

In [5]:
client.delay_seconds = 3.1 # prevent rate limiting
client.num_retries = 0

def get_papers(area_name: str, query: str, max_results: int) -> dict:

    cached_data = load_cached_search(area_name, query, max_results)

    if cached_data is not None:
        return cached_data

    search = arxiv.Search(
        query=query,
        max_results=max_results,
        sort_by=arxiv.SortCriterion.SubmittedDate,
        sort_order=arxiv.SortOrder.Descending
    )

    client.page_size = min(max_results, 100)
    papers = [paper_to_dict(paper) for paper in client.results(search)]

    search_data = {
        "area": area_name,
        "query": query,
        "max_results": max_results,
        "sort_by": "submittedDate",
        "sort_order": "descending",
        "fetched_at": datetime.now(timezone.utc).isoformat(),
        "papers": papers
    }

    cache_path = get_cache_path(area_name, query, max_results)
    cache_path.parent.mkdir(parents=True, exist_ok=True)

    json_text = json.dumps(search_data, indent=2, sort_keys=True, ensure_ascii=False)
    cache_path.write_text(json_text, encoding="utf-8")

    return search_data

### Collect Metadata

Load cached results or retrieve paper metadata for each configured search.

In [6]:
results_by_area = {}

for area_name, settings in collection_areas.items():
    query = get_search_query(settings["keywords"])
    max_results = settings["target"]

    print(f"Fetching papers for area '{area_name}' with query: {query}")

    search_data = get_papers(
        area_name, 
        query, 
        max_results
    )

    results_by_area[area_name] = search_data
    print(area_name, len(search_data["papers"]))

Fetching papers for area 'document_analysis_and_knowledge_access' with query: (abs:"document understanding" OR abs:"information extraction" OR abs:"retrieval augmented generation" OR abs:"table understanding")
document_analysis_and_knowledge_access 10
Fetching papers for area 'workflow_automation' with query: (abs:"ai agents" OR abs:"tool use" OR abs:"human oversight" OR abs:"process automation")
workflow_automation 10
Fetching papers for area 'ai_reliability_governance' with query: (abs:"hallucination detection" OR abs:"explainable AI" OR abs:"algorithmic bias" OR abs:"LLM evaluation")
ai_reliability_governance 10
Fetching papers for area 'finance_risk_analytics' with query: (abs:"financial forecasting" OR abs:"risk assessment" OR abs:"fraud detection" OR abs:"financial document analysis")
finance_risk_analytics 10
Fetching papers for area 'operations_supply_chain' with query: (abs:"supply chain optimization" OR abs:"inventory management" OR abs:"logistics planning" OR abs:"demand forecasting")
operations_supply_chain 10
Fetching papers for area 'customer_service' with query: (abs:"customer support" OR abs:"conversational Agents" OR abs:"sentiment analysis" OR abs:"customer feedback analysis")
customer_service 10
Fetching papers for area 'technology_implementation' with query: (abs:"model deployment" OR abs:"model efficiency" OR abs:"model routing" OR abs:"efficient inference")
technology_implementation 10
Fetching papers for area 'general' with query: (cat:cs.AI OR cat:cs.LG OR cat:cs.CL OR cat:cs.IR OR cat:cs.CV)
general 30

Removes duplicate papers, retain their collection areas, and save the combined catalog.

In [7]:
papers_by_id = {}

for area_name, search_data in results_by_area.items():

    for paper in search_data["papers"]:

        paper_id = re.sub(r"v\d+$", "", paper["id"]) # remove version suffix from ID

        if paper_id not in papers_by_id:
            record = paper.copy()

            record["collection_areas"] = []
            papers_by_id[paper_id] = record

        areas = papers_by_id[paper_id]["collection_areas"]

        if area_name not in areas:
            areas.append(area_name)

unique_papers = list(papers_by_id.values())
print("Unique papers:", len(unique_papers))

Unique papers: 95

In [8]:
missing_areas = set(collection_areas.keys()) - set(results_by_area.keys())

if missing_areas:
    raise ValueError(f"Searches still missing: {sorted(missing_areas)}")

if not unique_papers:
    raise ValueError("No papers to save.")

catalog_path = metadata_dr / "papers.jsonl"
catalog_path.parent.mkdir(parents=True, exist_ok=True)

with catalog_path.open("w", encoding="utf-8") as f:
    for paper in unique_papers:
        json_text = json.dumps(paper, ensure_ascii=False)
        f.write(json_text + "\n")

print(f"Saved {len(unique_papers)} papers to {catalog_path}")

Saved 95 papers to arxiv_data/metadata/papers.jsonl

Identify existing PDFs and calculate the space available within the dataset budget.

In [9]:
dataset_dir = Path("arxiv_data")
pdf_dir = dataset_dir / "pdfs"

inventory = []

for paper in unique_papers:
    filename = paper["id"].replace("/", "_") + ".pdf"
    pdf_path = pdf_dir / filename

    exists = pdf_path.exists()

    inventory.append({
       "id": paper["id"],
       "title": paper["title"],
       "already_downloaded": exists,
       "pdf_path": str(pdf_path),
       "size_bytes": pdf_path.stat().st_size if exists else 0
    })

download_inventory = pd.DataFrame(inventory)
display(download_inventory)

,id,title,already_downloaded,pdf_path,size_bytes
0,2609.22043v1,An Interpretable Memory Decision Controller fo...,False,arxiv_data/pdfs/2609.22043v1.pdf,0
1,2609.21863v1,"AutoRecLab: Describe the Experiment, Get the C...",False,arxiv_data/pdfs/2609.21863v1.pdf,0
2,2609.21626v1,One Prompt Does Not Fit All: Self-Meta-Evolve ...,False,arxiv_data/pdfs/2609.21626v1.pdf,0
3,2609.21600v1,Reducing Barriers to Academic Support: Evaluat...,False,arxiv_data/pdfs/2609.21600v1.pdf,0
4,2609.21573v1,Micro-Collaborative Poisoning: A Distributed A...,False,arxiv_data/pdfs/2609.21573v1.pdf,0
...,...,...,...,...,...
90,2609.21992v1,Moral Entropy: Auditing Bias and Uncertainty i...,False,arxiv_data/pdfs/2609.21992v1.pdf,0
91,2609.21989v1,Time series generation with spectrally aligned...,False,arxiv_data/pdfs/2609.21989v1.pdf,0
92,2609.21976v1,Multiplicative Optimism for Constant Regret in...,False,arxiv_data/pdfs/2609.21976v1.pdf,0
93,2609.21962v1,Learning Cardiac Features: ECG Biometrics Acro...,False,arxiv_data/pdfs/2609.21962v1.pdf,0
94,2609.21960v1,Schedule optimization for tau-leaping in maske...,False,arxiv_data/pdfs/2609.21960v1.pdf,0

Check the size of the dataset we have downloaded. Constraints are `<1 GB`

In [10]:
storage_budget = 900_000_000

used_bytes = sum(
    path.stat().st_size
    for path in dataset_dir.rglob("*")
    if path.is_file()
)

remaining_bytes = max(0, storage_budget - used_bytes)

print(f"Current dataset size: {used_bytes / 1_000_000_000:.3f} GB")
print(f"Available within budget: {remaining_bytes / 1_000_000_000:.3f} GB")

existing_count = int(download_inventory["already_downloaded"].sum())

print("Candidate papers:", len(download_inventory))
print("Already downloaded:", existing_count)
print("Missing PDFs:", len(download_inventory) - existing_count)

Current dataset size: 0.000 GB
Available within budget: 0.900 GB
Candidate papers: 95
Already downloaded: 0
Missing PDFs: 95

### Download PDFs

Download missing papers sequentially while enforcing request spacing and the storage budget.

In [12]:
dataset_dir = Path("arxiv_data")
pdf_dir = dataset_dir / "pdfs"
pdf_dir.mkdir(parents=True, exist_ok=True)

selected_papers = unique_papers
storage_limit = storage_budget    # 900 MB, leaving room below 1 GB

def folder_size():
    return sum(
        file.stat().st_size
        for file in dataset_dir.rglob("*")
        if file.is_file()
    )

request_interval = 3.1
last_request_started = time.monotonic()

for paper in selected_papers:

    pdf_url = paper.get("pdf_url")

    if not pdf_url:
        print("Skipping paper without PDF URL:", paper["title"])
        continue

    filename = paper["id"].replace("/", "_") + ".pdf"
    pdf_path = pdf_dir / filename
    temp_path = pdf_path.with_suffix(".part")

    if pdf_path.is_file():
        print("Already downloaded:", pdf_path.name)
        continue

    temp_path.unlink(missing_ok=True)
    available_bytes = storage_limit - folder_size()

    if available_bytes <= 0:
        print("Storage budget reached. Stopping.")
        break

 
    print("Downloading:", paper["title"], flush=True)
    downloaded_bytes = 0

    try:
        elapsed = time.monotonic() - last_request_started
        wait_seconds = max(0, request_interval - elapsed)
        time.sleep(wait_seconds)
    
        last_request_started = time.monotonic()
        
        with libreq.urlopen(pdf_url, timeout=60) as response:
            with temp_path.open("wb") as file:
                while True:
                    chunk = response.read(64 * 1024)
                    if not chunk:
                        break

                    if downloaded_bytes == 0 and not chunk.startswith(b"%PDF-"):
                        raise ValueError("Server response was not a PDF.")

                    if downloaded_bytes + len(chunk) > available_bytes:
                        raise ValueError("Download would exceed the storage budget.")

                    file.write(chunk)
                    downloaded_bytes += len(chunk)

        if downloaded_bytes == 0:
            raise ValueError("Server returned an empty file.")

        temp_path.replace(pdf_path)
        print(f"Saved {pdf_path.name}: {downloaded_bytes / 1_000_000:.2f} MB")

    except HTTPError as error:
        print(f"HTTP {error.code}: stopping downloads.")
        print(error.read().decode("utf-8", errors="replace")[:300])
        error.close()
        break

    except (OSError, ValueError) as error:
        print("Stopped:", error)
        break

    finally:
        temp_path.unlink(missing_ok=True)

print(f"\nDataset folder size: {folder_size() / 1_000_000:.2f} MB")
print("PDF location:", pdf_dir.resolve())

Already downloaded: 2609.22043v1.pdf
Already downloaded: 2609.21863v1.pdf
Already downloaded: 2609.21626v1.pdf
Already downloaded: 2609.21600v1.pdf
Already downloaded: 2609.21573v1.pdf
Already downloaded: 2609.20754v1.pdf
Already downloaded: 2609.19965v1.pdf
Already downloaded: 2609.19657v1.pdf
Already downloaded: 2609.19634v1.pdf
Already downloaded: 2609.19622v1.pdf
Already downloaded: 2609.22083v1.pdf
Already downloaded: 2609.22076v1.pdf
Already downloaded: 2609.22067v1.pdf
Already downloaded: 2609.21967v1.pdf
Already downloaded: 2609.21841v1.pdf
Already downloaded: 2609.21805v1.pdf
Already downloaded: 2609.21686v1.pdf
Already downloaded: 2609.21564v1.pdf
Already downloaded: 2609.21468v1.pdf
Already downloaded: 2609.21439v1.pdf
Already downloaded: 2609.21867v1.pdf
Already downloaded: 2609.21349v1.pdf
Already downloaded: 2609.21096v1.pdf
Already downloaded: 2609.19491v1.pdf
Already downloaded: 2609.18748v2.pdf
Already downloaded: 2609.18320v1.pdf
Already downloaded: 2609.18212v1.pdf
Already downloaded: 2609.18075v1.pdf
Already downloaded: 2609.18049v1.pdf
Already downloaded: 2609.16739v1.pdf
Already downloaded: 2609.21955v1.pdf
Already downloaded: 2609.20584v1.pdf
Already downloaded: 2609.20554v1.pdf
Already downloaded: 2609.19813v1.pdf
Already downloaded: 2609.19385v1.pdf
Already downloaded: 2609.18766v2.pdf
Already downloaded: 2609.18658v1.pdf
Already downloaded: 2609.18391v1.pdf
Already downloaded: 2609.18107v1.pdf
Already downloaded: 2609.17242v1.pdf
Already downloaded: 2609.17919v1.pdf
Already downloaded: 2609.17297v2.pdf
Already downloaded: 2609.14718v1.pdf
Already downloaded: 2609.13561v1.pdf
Already downloaded: 2609.11295v2.pdf
Already downloaded: 2609.06636v1.pdf
Already downloaded: 2609.04662v1.pdf
Already downloaded: 2609.00541v1.pdf
Already downloaded: 2608.30199v1.pdf
Already downloaded: 2608.28273v2.pdf
Already downloaded: 2609.21576v1.pdf
Already downloaded: 2609.21187v1.pdf
Already downloaded: 2609.19635v1.pdf
Already downloaded: 2609.19244v1.pdf
Already downloaded: 2609.18470v1.pdf
Already downloaded: 2609.18404v1.pdf
Already downloaded: 2609.18238v1.pdf
Already downloaded: 2609.17119v1.pdf
Already downloaded: 2609.17010v1.pdf
Already downloaded: 2609.21704v1.pdf
Already downloaded: 2609.20997v1.pdf
Already downloaded: 2609.20709v1.pdf
Already downloaded: 2609.19850v1.pdf
Already downloaded: 2609.19320v1.pdf
Already downloaded: 2609.18632v1.pdf
Already downloaded: 2609.17940v1.pdf
Already downloaded: 2609.17109v1.pdf
Downloading: Accelerated Decoding of Centroid Positional Encoding for Instance Segmentation
Saved 2609.16874v1.pdf: 1.16 MB
Downloading: When the World Lies: Backdoor Attacks on Latent World Models for Downstream Control
Saved 2609.15781v1.pdf: 2.11 MB
Downloading: Designer-RSI: Evolving Procedural Memory from User Traffic for Agentic Graphic Design
Saved 2609.22086v1.pdf: 26.03 MB
Downloading: Cross-sector generalization of accident-process role classification in occupational accident narratives
Saved 2609.22081v1.pdf: 1.13 MB
Downloading: OmniVBench: A Benchmark and Large-Scale Dataset for Omni Reference-to-Video Generation
Saved 2609.22069v1.pdf: 8.26 MB
Downloading: CodeMidas: Scaling Agentic Coding RL Environments from Code Itself
Saved 2609.22068v1.pdf: 0.56 MB
Downloading: BrainWideBench: Benchmarking large-scale pretraining and across-animal transfer in multi-region neural recordings
Saved 2609.22064v1.pdf: 6.52 MB
Downloading: Traffic Sign Recognition for Autonomous Driving Using Branched YOLOv2 and Geometric Features
Saved 2609.22060v1.pdf: 23.33 MB
Downloading: Predictable Failure in Multi-Hop Retrieval: Score-Distributional Confidence Scoring and Abstention
Saved 2609.22056v1.pdf: 0.28 MB
Downloading: Benchmarking World Models for Continual Learning on Compositional Tasks
Saved 2609.22055v1.pdf: 1.22 MB
Downloading: Particle Competition and Cooperation for Robust Graph Convolutional Network Learning Under Label Noise
Saved 2609.22053v1.pdf: 1.51 MB
Downloading: Available Guardrails: Certifying Selective Prediction across ML Systems
Saved 2609.22048v1.pdf: 1.28 MB
Downloading: $λ$-Controlled GRPO: Turning Flow-Matching Ratio Instability into a Budgeted Resource
Saved 2609.22041v1.pdf: 50.72 MB
Downloading: PRIME: Perception Feedback with Situational Memory Embeddings in VLA Models
Saved 2609.22040v1.pdf: 1.07 MB
Downloading: Gricea: An Open Science Platform for Conversational AI Research
Saved 2609.22039v1.pdf: 5.78 MB
Downloading: QuranicMMLU: A Cognitively-Aware Benchmark for Evaluating Generative AI Solutions on Quranic Linguistic Knowledge
Saved 2609.22038v1.pdf: 0.75 MB
Downloading: COMPLEX: A Closed-Form Certified Embedding of Multiparameter Persistence Modules
Saved 2609.22012v1.pdf: 0.70 MB
Downloading: DiaVLo: Diagnosing Behaviours of Vision-Language Models
Saved 2609.22008v1.pdf: 12.44 MB
Downloading: Abstention and Noise Filtering: Two Missing Primitives of Softmax Attention
Saved 2609.22005v1.pdf: 0.38 MB
Downloading: RecreationWorld: Scalable and Verifiable Environments for Hybrid Computer-Use Agents
Saved 2609.22000v1.pdf: 5.53 MB
Downloading: Bayesian Belief Layer for Controllable Opinion Dynamics in LLM Agents
Saved 2609.21997v1.pdf: 0.69 MB
Downloading: A Lie Detector Test for Language Models: Reading Knowledge a Model Won't Reveal
Saved 2609.21996v1.pdf: 0.45 MB
Downloading: Assessment of Machine Learning-Based Critical Heat Flux Models in the CTF Subchannel Code for Square Rod Bundle Prediction
Saved 2609.21995v1.pdf: 4.03 MB
Downloading: Moral Entropy: Auditing Bias and Uncertainty in Moral Judgment
Saved 2609.21992v1.pdf: 0.44 MB
Downloading: Time series generation with spectrally aligned latent flow matching
Saved 2609.21989v1.pdf: 1.42 MB
Downloading: Multiplicative Optimism for Constant Regret in Games
Saved 2609.21976v1.pdf: 0.79 MB
Downloading: Learning Cardiac Features: ECG Biometrics Across Time and~Exercise
Saved 2609.21962v1.pdf: 0.93 MB
Downloading: Schedule optimization for tau-leaping in masked discrete diffusion
Saved 2609.21960v1.pdf: 1.26 MB

Dataset folder size: 348.78 MB
PDF location: /Users/alexnguyen/Documents/GitHub/KPMG-1C-ai-research-intelligence-agent-for-business-insight-translation/notebooks/arxiv_data/pdfs

### Download Summary

Summarize the number and sizes of PDFs currently stored on disk.

In [13]:
from pathlib import Path

pdf_dir = Path("arxiv_data/pdfs")
pdfs = sorted(pdf_dir.glob("*.pdf"))

total_bytes = sum(pdf.stat().st_size for pdf in pdfs)

for pdf in pdfs:
    print(f"{pdf.name}: {pdf.stat().st_size / 1_000_000:.2f} MB")

print(f"\nPDF count: {len(pdfs)}")
print(f"Total PDF size: {total_bytes / 1_000_000:.2f} MB")
print(f"Total PDF size: {total_bytes / 1_000_000_000:.4f} GB")

if pdfs:
    average_mb = total_bytes / len(pdfs) / 1_000_000
    print(f"Average per PDF: {average_mb:.2f} MB")

2608.28273v2.pdf: 3.30 MB
2608.30199v1.pdf: 7.83 MB
2609.00541v1.pdf: 0.93 MB
2609.04662v1.pdf: 3.60 MB
2609.06636v1.pdf: 2.08 MB
2609.11295v2.pdf: 1.59 MB
2609.13561v1.pdf: 0.85 MB
2609.14718v1.pdf: 0.24 MB
2609.15781v1.pdf: 2.11 MB
2609.16739v1.pdf: 0.60 MB
2609.16874v1.pdf: 1.16 MB
2609.17010v1.pdf: 3.56 MB
2609.17109v1.pdf: 0.27 MB
2609.17119v1.pdf: 1.44 MB
2609.17242v1.pdf: 2.37 MB
2609.17297v2.pdf: 0.37 MB
2609.17919v1.pdf: 0.77 MB
2609.17940v1.pdf: 0.29 MB
2609.18049v1.pdf: 1.24 MB
2609.18075v1.pdf: 2.14 MB
2609.18107v1.pdf: 0.87 MB
2609.18212v1.pdf: 3.61 MB
2609.18238v1.pdf: 0.97 MB
2609.18320v1.pdf: 0.48 MB
2609.18391v1.pdf: 1.68 MB
2609.18404v1.pdf: 3.23 MB
2609.18470v1.pdf: 5.83 MB
2609.18632v1.pdf: 4.05 MB
2609.18658v1.pdf: 0.18 MB
2609.18748v2.pdf: 5.73 MB
2609.18766v2.pdf: 2.86 MB
2609.19244v1.pdf: 2.38 MB
2609.19320v1.pdf: 3.54 MB
2609.19385v1.pdf: 8.97 MB
2609.19491v1.pdf: 2.21 MB
2609.19622v1.pdf: 4.11 MB
2609.19634v1.pdf: 35.98 MB
2609.19635v1.pdf: 0.64 MB
2609.19657v1.pdf: 0.59 MB
2609.19813v1.pdf: 0.55 MB
2609.19850v1.pdf: 4.66 MB
2609.19965v1.pdf: 2.80 MB
2609.20554v1.pdf: 1.88 MB
2609.20584v1.pdf: 0.54 MB
2609.20709v1.pdf: 1.12 MB
2609.20754v1.pdf: 0.39 MB
2609.20997v1.pdf: 1.28 MB
2609.21096v1.pdf: 1.70 MB
2609.21187v1.pdf: 0.28 MB
2609.21349v1.pdf: 1.94 MB
2609.21439v1.pdf: 1.12 MB
2609.21468v1.pdf: 6.63 MB
2609.21564v1.pdf: 1.25 MB
2609.21573v1.pdf: 0.79 MB
2609.21576v1.pdf: 1.91 MB
2609.21600v1.pdf: 1.26 MB
2609.21626v1.pdf: 1.08 MB
2609.21686v1.pdf: 0.98 MB
2609.21704v1.pdf: 0.19 MB
2609.21805v1.pdf: 0.35 MB
2609.21841v1.pdf: 1.38 MB
2609.21863v1.pdf: 0.63 MB
2609.21867v1.pdf: 5.05 MB
2609.21955v1.pdf: 11.37 MB
2609.21960v1.pdf: 1.26 MB
2609.21962v1.pdf: 0.93 MB
2609.21967v1.pdf: 0.93 MB
2609.21976v1.pdf: 0.79 MB
2609.21989v1.pdf: 1.42 MB
2609.21992v1.pdf: 0.44 MB
2609.21995v1.pdf: 4.03 MB
2609.21996v1.pdf: 0.45 MB
2609.21997v1.pdf: 0.69 MB
2609.22000v1.pdf: 5.53 MB
2609.22005v1.pdf: 0.38 MB
2609.22008v1.pdf: 12.44 MB
2609.22012v1.pdf: 0.70 MB
2609.22038v1.pdf: 0.75 MB
2609.22039v1.pdf: 5.78 MB
2609.22040v1.pdf: 1.07 MB
2609.22041v1.pdf: 50.72 MB
2609.22043v1.pdf: 2.10 MB
2609.22048v1.pdf: 1.28 MB
2609.22053v1.pdf: 1.51 MB
2609.22055v1.pdf: 1.22 MB
2609.22056v1.pdf: 0.28 MB
2609.22060v1.pdf: 23.33 MB
2609.22064v1.pdf: 6.52 MB
2609.22067v1.pdf: 0.77 MB
2609.22068v1.pdf: 0.56 MB
2609.22069v1.pdf: 8.26 MB
2609.22076v1.pdf: 1.05 MB
2609.22081v1.pdf: 1.13 MB
2609.22083v1.pdf: 10.20 MB
2609.22086v1.pdf: 26.03 MB

PDF count: 95
Total PDF size: 348.37 MB
Total PDF size: 0.3484 GB
Average per PDF: 3.67 MB

### PDF Integrity Checks

Flag files whose PDF header or ending marker is missing.

This cell checks for any files that might have failed to download properly

In [14]:

checks = []

for pdf in sorted(Path("arxiv_data/pdfs").glob("*.pdf")):
    size = pdf.stat().st_size

    with pdf.open("rb") as file:
        header = file.read(5)
        file.seek(max(0, size - 4096))
        ending = file.read()

    checks.append({
        "filename": pdf.name,
        "size_mb": size / 1_000_000,
        "pdf_header": header == b"%PDF-",
        "eof_near_end": b"%%EOF" in ending,
    })

pdf_checks = pd.DataFrame(
    checks,
    columns=["filename", "size_mb", "pdf_header", "eof_near_end"],
)

suspect_files = pdf_checks[
    (pdf_checks["pdf_header"] == False)
    | (pdf_checks["eof_near_end"] == False)
]

display(suspect_files)

Empty DataFrame
Columns: [filename, size_mb, pdf_header, eof_near_end]
Index: []

### Optional File Cleanup

Record and delete files flagged by the preceding integrity checks.

The cell below removes any suspicious files. **Only run if the above cell found any mismatches**

In [15]:
pdf_dir = dataset_dir / "pdfs"

# Record what was excluded and why.
metadata_dir = dataset_dir / "metadata"
metadata_dir.mkdir(parents=True, exist_ok=True)
suspect_files.assign(
    exclusion_reason="Missing PDF header or ending marker"
).to_csv(metadata_dir / "excluded_pdfs.csv", index=False)

removed = 0

for filename in suspect_files["filename"]:
    pdf_path = pdf_dir / filename

    if pdf_path.is_file():
        pdf_path.unlink()
        removed += 1
        print("Deleted:", filename)

print(f"\nRemoved {removed} PDFs.")

Removed 0 PDFs.

### Text Extraction and EDA

Extract page text, measure document properties, and attach arXiv tags and collection areas.

This cell gives some basic information about the PDFs as well as data about the collection of papers

In [18]:
pdf_dir = Path("arxiv_data/pdfs")

rows = []
pages_by_paper = {}

for pdf in sorted(pdf_dir.glob("*.pdf")):
    row = {
        "filename": pdf.name,
        "size_mb": pdf.stat().st_size / 1_000_000,
        "pages": None,
        "approx_words": None,
        "low_text_pages": None,
        "extraction_error": "",
    }

    try:
        reader = PdfReader(pdf)
        page_texts = [page.extract_text() or "" for page in reader.pages]

        # Keep page boundaries for inspection and future citations.
        pages_by_paper[pdf.name] = page_texts

        row.update({
            "pages": len(page_texts),
            "approx_words": sum(len(text.split()) for text in page_texts),
            "low_text_pages": sum(
                len(text.strip()) < 100 for text in page_texts
            ),
        })

    except Exception as error:
        row["extraction_error"] = str(error)

    rows.append(row)

df = pd.DataFrame(rows)

titles_by_filename = {
    paper["id"].replace("/", "_") + ".pdf": paper["title"]
    for paper in unique_papers
}

df["title"] = df["filename"].map(titles_by_filename)

areas_by_filename = {
    paper["id"].replace("/", "_") + ".pdf": paper["collection_areas"]
    for paper in unique_papers
}

df["collection_areas"] = df["filename"].map(areas_by_filename)

categories_by_filename = {
    paper["id"].replace("/", "_") + ".pdf": paper["arxiv_categories"]
    for paper in unique_papers
}

df["arxiv_categories"] = df["filename"].map(categories_by_filename)

# Official names for categories in this collection: https://arxiv.org/category_taxonomy
arxiv_category_names = {
    "cs.AI": "Artificial Intelligence",
    "cs.CL": "Computation and Language",
    "cs.CR": "Cryptography and Security",
    "cs.CV": "Computer Vision and Pattern Recognition",
    "cs.CY": "Computers and Society",
    "cs.DB": "Databases",
    "cs.GR": "Graphics",
    "cs.GT": "Computer Science and Game Theory",
    "cs.HC": "Human-Computer Interaction",
    "cs.IR": "Information Retrieval",
    "cs.LG": "Machine Learning",
    "cs.MA": "Multiagent Systems",
    "cs.MM": "Multimedia",
    "cs.NI": "Networking and Internet Architecture",
    "cs.PF": "Performance",
    "cs.RO": "Robotics",
    "cs.SD": "Sound",
    "cs.SE": "Software Engineering",
    "econ.EM": "Econometrics",
    "econ.GN": "General Economics",
    "eess.IV": "Image and Video Processing",
    "eess.SP": "Signal Processing",
    "eess.SY": "Systems and Control",
    "hep-th": "High Energy Physics - Theory",
    "math-ph": "Mathematical Physics",
    "math.AG": "Algebraic Geometry",
    "math.AT": "Algebraic Topology",
    "math.OC": "Optimization and Control",
    "math.ST": "Statistics Theory",
    "physics.flu-dyn": "Fluid Dynamics",
    "q-bio.NC": "Neurons and Cognition",
    "q-bio.TO": "Tissues and Organs",
    "stat.AP": "Applications",
    "stat.ML": "Machine Learning",
}

df["arxiv_category_names"] = df["arxiv_categories"].apply(
    lambda codes: [arxiv_category_names.get(code, code) for code in codes]
    if isinstance(codes, list) else pd.NA
)

leading_columns = ["title", "arxiv_category_names", "collection_areas"]
df = df[leading_columns + [col for col in df.columns if col not in leading_columns]]

# Format a display copy so the analysis data and CSV retain their precision.
display_df = df.copy()
display_df["size_mb"] = display_df["size_mb"].round(2)
count_columns = ["pages", "approx_words", "low_text_pages"]
display_df[count_columns] = display_df[count_columns].astype("Int64")
display_df = display_df.rename(columns={
    "title": "Title",
    "arxiv_category_names": "Categories",
    "collection_areas": "Areas",
    "filename": "File",
    "size_mb": "MB",
    "pages": "Pages",
    "approx_words": "Words (approx.)",
    "low_text_pages": "Low-text pages",
    "extraction_error": "Error",
    "arxiv_categories": "Category codes",
})

with pd.option_context("display.precision", 2, "display.max_colwidth", 60):
    display(display_df)
    display(
        df[["size_mb", "pages", "approx_words"]]
        .describe()
        .rename(columns={"size_mb": "MB", "pages": "Pages", "approx_words": "Words (approx.)"})
        .round(2)
    )

metadata_dir = Path("arxiv_data") / "metadata"
metadata_dir.mkdir(parents=True, exist_ok=True)
df.to_csv(metadata_dir / "paper_eda.csv", index=False)

Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
Skipping broken line b'07ac   07b2   1f130': Odd-length string
Skipping broken line b'07b4   07c6   1f137': Odd-length string
Got invalid hex string: Odd-length string (b'1f12f')
Got invalid hex string: Odd-length string (b'1f16b')
Got invalid hex string: Odd-length string (b'1f16a')
Got invalid hex string: Odd-length string (b'1f850')
Got invalid hex string: Odd-length string (b'1f852')
Skipping broken line b'07ac   07b2   1f130': Odd-length string
Skipping broken line b'07b4   07c6   1f137': Odd-length string
Got invalid hex string: Odd-length string (b'1f12f')
Got invalid hex string: Odd-length string (b'1f16b')
Got invalid hex string: Odd-length string (b'1f16a')
Got invalid hex string: Odd-length string (b'1f850')
Got invalid hex string: Odd-length string (b'1f852')

,Title,Categories,Areas,File,MB,Pages,Words (approx.),Low-text pages,Error,Category codes
0,Learning to Transfer Across Modes: Towards Unified Urban...,[Machine Learning],[operations_supply_chain],2608.28273v2.pdf,3.30,10,7947,0,,[cs.LG]
1,A High-Resolution Synthetic EV Charging Dataset for Cold...,[Systems and Control],[operations_supply_chain],2608.30199v1.pdf,7.83,10,4245,0,,[eess.SY]
2,Optimal Uniform Pricing for Multi-Interval Dispatch with...,"[Systems and Control, Econometrics]",[operations_supply_chain],2609.00541v1.pdf,0.93,5,3985,0,,"[eess.SY, econ.EM]"
3,Is Forecasting Accuracy Enough? A Comparative Study of T...,[Signal Processing],[operations_supply_chain],2609.04662v1.pdf,3.60,14,10120,0,,[eess.SP]
4,TD-STGT: A Spatio-Temporal Graph Transformer for Mobile ...,"[Systems and Control, Artificial Intelligence, Machine L...",[operations_supply_chain],2609.06636v1.pdf,2.08,6,3356,0,,"[eess.SY, cs.AI, cs.LG]"
...,...,...,...,...,...,...,...,...,...,...
90,OmniVBench: A Benchmark and Large-Scale Dataset for Omni...,[Computer Vision and Pattern Recognition],[general],2609.22069v1.pdf,8.26,32,14263,0,,[cs.CV]
91,APort Vault: Benchmarking AI Agent Payment Authorization...,[Cryptography and Security],[workflow_automation],2609.22076v1.pdf,1.05,21,9083,0,,[cs.CR]
92,Cross-sector generalization of accident-process role cla...,[Computation and Language],[general],2609.22081v1.pdf,1.13,28,15106,0,,[cs.CL]
93,MintAct: A Unified Visual Agent for Digital Environments,[Computer Vision and Pattern Recognition],"[workflow_automation, general]",2609.22083v1.pdf,10.20,31,15295,0,,[cs.CV]
94,Designer-RSI: Evolving Procedural Memory from User Traff...,"[Artificial Intelligence, Computer Vision and Pattern Re...",[general],2609.22086v1.pdf,26.03,30,14516,0,,"[cs.AI, cs.CV]"

          MB   Pages  Words (approx.)
count  95.00   95.00            95.00
mean    3.67   21.16         10194.19
std     7.23   19.93          7264.20
min     0.18    4.00          2533.00
25%     0.76   10.00          5388.00
50%     1.28   15.00          7693.00
75%     3.55   27.50         13309.00
max    50.72  151.00         46527.00

### Some statistics of the sample data at a glance

The next cell provides some insight into the dataset's numerical features (e.g categories, word count)

In [37]:
print(f"Top 10 arXiv categories in the dataset:")
display(df["arxiv_category_names"].explode().value_counts().head(10))

area_counts = df["collection_areas"].explode().value_counts()
area_proportions = (area_counts / area_counts.sum() * 100).round(1)
display(area_proportions.map(lambda value: f"{value:.1f}%"))

print(f"Top 10 papers with the most words:")
display(df.nlargest(10, "approx_words")[["title", "approx_words", "pages","arxiv_category_names", "collection_areas"]])

Top 10 arXiv categories in the dataset:

arxiv_category_names
Machine Learning                           34
Artificial Intelligence                    27
Computation and Language                   23
Computer Vision and Pattern Recognition    12
Human-Computer Interaction                  7
Cryptography and Security                   6
Robotics                                    5
Information Retrieval                       4
Computers and Society                       4
Systems and Control                         4
Name: count, dtype: int64

collection_areas
general                                   30.0%
operations_supply_chain                   10.0%
technology_implementation                 10.0%
ai_reliability_governance                 10.0%
customer_service                          10.0%
finance_risk_analytics                    10.0%
document_analysis_and_knowledge_access    10.0%
workflow_automation                       10.0%
Name: count, dtype: object

Top 10 papers with the most words:

,title,approx_words,pages,arxiv_category_names,collection_areas
42,Does Training on Future Data Pay? Look-Ahead B...,46527,151,[General Economics],[finance_risk_analytics]
87,BrainWideBench: Benchmarking large-scale pretr...,40350,87,"[Machine Learning, Neurons and Cognition]",[general]
73,RecreationWorld: Scalable and Verifiable Envir...,24722,47,"[Computation and Language, Software Engineering]",[general]
67,Multiplicative Optimism for Constant Regret in...,22665,61,"[Computer Science and Game Theory, Machine Lea...",[general]
76,COMPLEX: A Closed-Form Certified Embedding of ...,22610,40,"[Machine Learning, Algebraic Topology]",[general]
88,Value-Sensitive Delegation in Everyday AI Agen...,21284,22,"[Human-Computer Interaction, Artificial Intell...","[workflow_automation, general]"
31,Characterizing Web Search by Conversational LL...,20523,57,"[Artificial Intelligence, Information Retrieval]",[customer_service]
34,Efficiently Linking Unstructured Data for Mult...,20267,23,"[Databases, Artificial Intelligence]",[ai_reliability_governance]
14,Trajectory CPHD Filtering for Multiple Turning...,19204,31,[Signal Processing],[finance_risk_analytics]
49,From Memory to Behavior: A Behavior-Aware Role...,18663,33,"[Computation and Language, Artificial Intellig...",[ai_reliability_governance]